// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjz1uhez7T_P89BhkYz-pjQPyHR7wSRP4',
    appId: '1:1076717578996:web:b25b7586ae8421250dcca1',
    messagingSenderId: '1076717578996',
    projectId: 'tiktokchel-abc-xyz',
    authDomain: 'tiktokchel-abc-xyz.firebaseapp.com',
    storageBucket: 'tiktokchel-abc-xyz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8EtBy_LXonlIeQyZXxffvdQo64GG-qY',
    appId: '1:1076717578996:android:5f05dc7ece96f7790dcca1',
    messagingSenderId: '1076717578996',
    projectId: 'tiktokchel-abc-xyz',
    storageBucket: 'tiktokchel-abc-xyz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDi0Ih6udCL2gHAAXR5rdvP7swGBLluiE',
    appId: '1:1076717578996:ios:c31709b189a3f2af0dcca1',
    messagingSenderId: '1076717578996',
    projectId: 'tiktokchel-abc-xyz',
    storageBucket: 'tiktokchel-abc-xyz.appspot.com',
    iosBundleId: 'com.example.tiktokChallenge',
  );
}
